// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countExpenseApprovals = `-- name: CountExpenseApprovals :one
SELECT count(*) FROM expense_approvals
WHERE expense_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountExpenseApprovals(ctx context.Context, expenseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseApprovals, expenseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (household_id, name, amount_minor, frequency, category, added_by, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, household_id, name, amount_minor, frequency, category, added_by, status, created_at, updated_at, deleted_at
`

type CreateExpenseParams struct {
	HouseholdID uuid.UUID
	Name        string
	AmountMinor int64
	Frequency   string
	Category    string
	AddedBy     uuid.UUID
	Status      string
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.HouseholdID,
		arg.Name,
		arg.AmountMinor,
		arg.Frequency,
		arg.Category,
		arg.AddedBy,
		arg.Status,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Frequency,
		&i.Category,
		&i.AddedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT id, household_id, name, amount_minor, frequency, category, added_by, status, created_at, updated_at, deleted_at FROM expenses
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetExpenseParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.HouseholdID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Frequency,
		&i.Category,
		&i.AddedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpenseApprovalsByHousehold = `-- name: ListExpenseApprovalsByHousehold :many
SELECT a.expense_id, a.user_id
FROM expense_approvals a
JOIN expenses e ON e.id = a.expense_id AND e.deleted_at IS NULL
WHERE e.household_id = $1 AND a.deleted_at IS NULL
`

type ListExpenseApprovalsByHouseholdRow struct {
	ExpenseID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ListExpenseApprovalsByHousehold(ctx context.Context, householdID uuid.UUID) ([]ListExpenseApprovalsByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listExpenseApprovalsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseApprovalsByHouseholdRow
	for rows.Next() {
		var i ListExpenseApprovalsByHouseholdRow
		if err := rows.Scan(&i.ExpenseID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, household_id, name, amount_minor, frequency, category, added_by, status, created_at, updated_at, deleted_at FROM expenses
WHERE household_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
`

type ListExpensesParams struct {
	HouseholdID uuid.UUID
	Status      *string
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses, arg.HouseholdID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.AmountMinor,
			&i.Frequency,
			&i.Category,
			&i.AddedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExpenseApproved = `-- name: SetExpenseApproved :exec
UPDATE expenses SET status = 'approved'
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetExpenseApproved(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setExpenseApproved, id)
	return err
}

const softDeleteExpense = `-- name: SoftDeleteExpense :execrows
UPDATE expenses SET deleted_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteExpenseParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExpense, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET name         = coalesce($1, name),
    amount_minor = coalesce($2, amount_minor),
    frequency    = coalesce($3, frequency),
    category     = coalesce($4, category)
WHERE id = $5 AND household_id = $6 AND deleted_at IS NULL
RETURNING id, household_id, name, amount_minor, frequency, category, added_by, status, created_at, updated_at, deleted_at
`

type UpdateExpenseParams struct {
	Name        *string
	AmountMinor *int64
	Frequency   *string
	Category    *string
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.Name,
		arg.AmountMinor,
		arg.Frequency,
		arg.Category,
		arg.ID,
		arg.HouseholdID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.AmountMinor,
		&i.Frequency,
		&i.Category,
		&i.AddedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertExpenseApproval = `-- name: UpsertExpenseApproval :execrows
INSERT INTO expense_approvals (expense_id, user_id)
VALUES ($1, $2)
ON CONFLICT (expense_id, user_id)
DO UPDATE SET deleted_at = NULL
WHERE expense_approvals.deleted_at IS NOT NULL
`

type UpsertExpenseApprovalParams struct {
	ExpenseID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpsertExpenseApproval(ctx context.Context, arg UpsertExpenseApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertExpenseApproval, arg.ExpenseID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
