// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSavingsPot = `-- name: CreateSavingsPot :one
INSERT INTO savings_pots (household_id, name, current_minor, target_minor, monthly_contribution_minor, emoji)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, household_id, name, current_minor, target_minor, monthly_contribution_minor, emoji, created_at, updated_at, deleted_at
`

type CreateSavingsPotParams struct {
	HouseholdID              uuid.UUID
	Name                     string
	CurrentMinor             int64
	TargetMinor              int64
	MonthlyContributionMinor int64
	Emoji                    string
}

func (q *Queries) CreateSavingsPot(ctx context.Context, arg CreateSavingsPotParams) (SavingsPot, error) {
	row := q.db.QueryRow(ctx, createSavingsPot,
		arg.HouseholdID,
		arg.Name,
		arg.CurrentMinor,
		arg.TargetMinor,
		arg.MonthlyContributionMinor,
		arg.Emoji,
	)
	var i SavingsPot
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.CurrentMinor,
		&i.TargetMinor,
		&i.MonthlyContributionMinor,
		&i.Emoji,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIncomeByUserID = `-- name: GetIncomeByUserID :one
SELECT id, household_id, user_id, gross_monthly_minor, net_monthly_minor, created_at, updated_at, deleted_at FROM incomes WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIncomeByUserID(ctx context.Context, userID uuid.UUID) (Income, error) {
	row := q.db.QueryRow(ctx, getIncomeByUserID, userID)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.GrossMonthlyMinor,
		&i.NetMonthlyMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMonthlySnapshot = `-- name: GetMonthlySnapshot :one
SELECT household_id, month, total_expenses_minor, created_at, updated_at, deleted_at FROM monthly_snapshots
WHERE household_id = $1 AND month = $2 AND deleted_at IS NULL
`

type GetMonthlySnapshotParams struct {
	HouseholdID uuid.UUID
	Month       pgtype.Date
}

func (q *Queries) GetMonthlySnapshot(ctx context.Context, arg GetMonthlySnapshotParams) (MonthlySnapshot, error) {
	row := q.db.QueryRow(ctx, getMonthlySnapshot, arg.HouseholdID, arg.Month)
	var i MonthlySnapshot
	err := row.Scan(
		&i.HouseholdID,
		&i.Month,
		&i.TotalExpensesMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSavingsPot = `-- name: GetSavingsPot :one
SELECT id, household_id, name, current_minor, target_minor, monthly_contribution_minor, emoji, created_at, updated_at, deleted_at FROM savings_pots
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetSavingsPotParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) GetSavingsPot(ctx context.Context, arg GetSavingsPotParams) (SavingsPot, error) {
	row := q.db.QueryRow(ctx, getSavingsPot, arg.ID, arg.HouseholdID)
	var i SavingsPot
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.CurrentMinor,
		&i.TargetMinor,
		&i.MonthlyContributionMinor,
		&i.Emoji,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaxInfo = `-- name: GetTaxInfo :one
SELECT user_id, gross_monthly_minor, tax_code, tax_system, tax_year, marital_status, pension_contribution_percent, has_student_loan, student_loan_plan, created_at, updated_at, deleted_at FROM tax_info WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTaxInfo(ctx context.Context, userID uuid.UUID) (TaxInfo, error) {
	row := q.db.QueryRow(ctx, getTaxInfo, userID)
	var i TaxInfo
	err := row.Scan(
		&i.UserID,
		&i.GrossMonthlyMinor,
		&i.TaxCode,
		&i.TaxSystem,
		&i.TaxYear,
		&i.MaritalStatus,
		&i.PensionContributionPercent,
		&i.HasStudentLoan,
		&i.StudentLoanPlan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listISAsByHousehold = `-- name: ListISAsByHousehold :many
SELECT i.id, i.household_id, i.user_id, i.type, i.balance_minor, i.contributions_this_year_minor, i.annual_allowance_minor, i.created_at, i.updated_at, i.deleted_at, u.name AS member_name
FROM isas i
JOIN users u ON u.id = i.user_id
WHERE i.household_id = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at
`

type ListISAsByHouseholdRow struct {
	ID                         uuid.UUID
	HouseholdID                uuid.UUID
	UserID                     uuid.UUID
	Type                       string
	BalanceMinor               int64
	ContributionsThisYearMinor int64
	AnnualAllowanceMinor       int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  *time.Time
	MemberName                 string
}

func (q *Queries) ListISAsByHousehold(ctx context.Context, householdID uuid.UUID) ([]ListISAsByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listISAsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListISAsByHouseholdRow
	for rows.Next() {
		var i ListISAsByHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.Type,
			&i.BalanceMinor,
			&i.ContributionsThisYearMinor,
			&i.AnnualAllowanceMinor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByHousehold = `-- name: ListIncomesByHousehold :many
SELECT i.id, i.household_id, i.user_id, i.gross_monthly_minor, i.net_monthly_minor, i.created_at, i.updated_at, i.deleted_at, u.name AS member_name
FROM incomes i
JOIN users u ON u.id = i.user_id
WHERE i.household_id = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at
`

type ListIncomesByHouseholdRow struct {
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	GrossMonthlyMinor int64
	NetMonthlyMinor   int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
	MemberName        string
}

func (q *Queries) ListIncomesByHousehold(ctx context.Context, householdID uuid.UUID) ([]ListIncomesByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listIncomesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomesByHouseholdRow
	for rows.Next() {
		var i ListIncomesByHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.GrossMonthlyMinor,
			&i.NetMonthlyMinor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPensionsByHousehold = `-- name: ListPensionsByHousehold :many
SELECT p.id, p.household_id, p.user_id, p.current_value_minor, p.target_minor, p.created_at, p.updated_at, p.deleted_at, u.name AS member_name
FROM pensions p
JOIN users u ON u.id = p.user_id
WHERE p.household_id = $1 AND p.deleted_at IS NULL
ORDER BY p.created_at
`

type ListPensionsByHouseholdRow struct {
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	CurrentValueMinor int64
	TargetMinor       int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
	MemberName        string
}

func (q *Queries) ListPensionsByHousehold(ctx context.Context, householdID uuid.UUID) ([]ListPensionsByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, listPensionsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPensionsByHouseholdRow
	for rows.Next() {
		var i ListPensionsByHouseholdRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.UserID,
			&i.CurrentValueMinor,
			&i.TargetMinor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsPots = `-- name: ListSavingsPots :many
SELECT id, household_id, name, current_minor, target_minor, monthly_contribution_minor, emoji, created_at, updated_at, deleted_at FROM savings_pots
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListSavingsPots(ctx context.Context, householdID uuid.UUID) ([]SavingsPot, error) {
	rows, err := q.db.Query(ctx, listSavingsPots, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsPot
	for rows.Next() {
		var i SavingsPot
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.CurrentMinor,
			&i.TargetMinor,
			&i.MonthlyContributionMinor,
			&i.Emoji,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSavingsPot = `-- name: SoftDeleteSavingsPot :execrows
UPDATE savings_pots SET deleted_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteSavingsPotParams struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
}

func (q *Queries) SoftDeleteSavingsPot(ctx context.Context, arg SoftDeleteSavingsPotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSavingsPot, arg.ID, arg.HouseholdID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSavingsPot = `-- name: UpdateSavingsPot :one
UPDATE savings_pots
SET name                       = coalesce($1, name),
    current_minor              = coalesce($2, current_minor),
    target_minor               = coalesce($3, target_minor),
    monthly_contribution_minor = coalesce($4, monthly_contribution_minor),
    emoji                      = coalesce($5, emoji)
WHERE id = $6 AND household_id = $7 AND deleted_at IS NULL
RETURNING id, household_id, name, current_minor, target_minor, monthly_contribution_minor, emoji, created_at, updated_at, deleted_at
`

type UpdateSavingsPotParams struct {
	Name                     *string
	CurrentMinor             *int64
	TargetMinor              *int64
	MonthlyContributionMinor *int64
	Emoji                    *string
	ID                       uuid.UUID
	HouseholdID              uuid.UUID
}

func (q *Queries) UpdateSavingsPot(ctx context.Context, arg UpdateSavingsPotParams) (SavingsPot, error) {
	row := q.db.QueryRow(ctx, updateSavingsPot,
		arg.Name,
		arg.CurrentMinor,
		arg.TargetMinor,
		arg.MonthlyContributionMinor,
		arg.Emoji,
		arg.ID,
		arg.HouseholdID,
	)
	var i SavingsPot
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.CurrentMinor,
		&i.TargetMinor,
		&i.MonthlyContributionMinor,
		&i.Emoji,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertISA = `-- name: UpsertISA :one
INSERT INTO isas (household_id, user_id, type, balance_minor, contributions_this_year_minor, annual_allowance_minor)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) WHERE deleted_at IS NULL
DO UPDATE SET type                          = excluded.type,
              balance_minor                 = excluded.balance_minor,
              contributions_this_year_minor = excluded.contributions_this_year_minor,
              annual_allowance_minor        = excluded.annual_allowance_minor
RETURNING id, household_id, user_id, type, balance_minor, contributions_this_year_minor, annual_allowance_minor, created_at, updated_at, deleted_at
`

type UpsertISAParams struct {
	HouseholdID                uuid.UUID
	UserID                     uuid.UUID
	Type                       string
	BalanceMinor               int64
	ContributionsThisYearMinor int64
	AnnualAllowanceMinor       int64
}

func (q *Queries) UpsertISA(ctx context.Context, arg UpsertISAParams) (Isa, error) {
	row := q.db.QueryRow(ctx, upsertISA,
		arg.HouseholdID,
		arg.UserID,
		arg.Type,
		arg.BalanceMinor,
		arg.ContributionsThisYearMinor,
		arg.AnnualAllowanceMinor,
	)
	var i Isa
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.Type,
		&i.BalanceMinor,
		&i.ContributionsThisYearMinor,
		&i.AnnualAllowanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertIncome = `-- name: UpsertIncome :one
INSERT INTO incomes (household_id, user_id, gross_monthly_minor, net_monthly_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) WHERE deleted_at IS NULL
DO UPDATE SET gross_monthly_minor = excluded.gross_monthly_minor,
              net_monthly_minor   = excluded.net_monthly_minor
RETURNING id, household_id, user_id, gross_monthly_minor, net_monthly_minor, created_at, updated_at, deleted_at
`

type UpsertIncomeParams struct {
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	GrossMonthlyMinor int64
	NetMonthlyMinor   int64
}

func (q *Queries) UpsertIncome(ctx context.Context, arg UpsertIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, upsertIncome,
		arg.HouseholdID,
		arg.UserID,
		arg.GrossMonthlyMinor,
		arg.NetMonthlyMinor,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.GrossMonthlyMinor,
		&i.NetMonthlyMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertMonthlySnapshot = `-- name: UpsertMonthlySnapshot :exec
INSERT INTO monthly_snapshots (household_id, month, total_expenses_minor)
VALUES ($1, $2, $3)
ON CONFLICT (household_id, month)
DO UPDATE SET total_expenses_minor = excluded.total_expenses_minor
`

type UpsertMonthlySnapshotParams struct {
	HouseholdID        uuid.UUID
	Month              pgtype.Date
	TotalExpensesMinor int64
}

func (q *Queries) UpsertMonthlySnapshot(ctx context.Context, arg UpsertMonthlySnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertMonthlySnapshot, arg.HouseholdID, arg.Month, arg.TotalExpensesMinor)
	return err
}

const upsertPension = `-- name: UpsertPension :one
INSERT INTO pensions (household_id, user_id, current_value_minor, target_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) WHERE deleted_at IS NULL
DO UPDATE SET current_value_minor = excluded.current_value_minor,
              target_minor        = excluded.target_minor
RETURNING id, household_id, user_id, current_value_minor, target_minor, created_at, updated_at, deleted_at
`

type UpsertPensionParams struct {
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	CurrentValueMinor int64
	TargetMinor       int64
}

func (q *Queries) UpsertPension(ctx context.Context, arg UpsertPensionParams) (Pension, error) {
	row := q.db.QueryRow(ctx, upsertPension,
		arg.HouseholdID,
		arg.UserID,
		arg.CurrentValueMinor,
		arg.TargetMinor,
	)
	var i Pension
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.CurrentValueMinor,
		&i.TargetMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertTaxInfo = `-- name: UpsertTaxInfo :one
INSERT INTO tax_info (user_id, gross_monthly_minor, tax_code, tax_system, tax_year,
                      marital_status, pension_contribution_percent, has_student_loan, student_loan_plan)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id)
DO UPDATE SET gross_monthly_minor          = excluded.gross_monthly_minor,
              tax_code                     = excluded.tax_code,
              tax_system                   = excluded.tax_system,
              tax_year                     = excluded.tax_year,
              marital_status               = excluded.marital_status,
              pension_contribution_percent = excluded.pension_contribution_percent,
              has_student_loan             = excluded.has_student_loan,
              student_loan_plan            = excluded.student_loan_plan,
              deleted_at                   = NULL
RETURNING user_id, gross_monthly_minor, tax_code, tax_system, tax_year, marital_status, pension_contribution_percent, has_student_loan, student_loan_plan, created_at, updated_at, deleted_at
`

type UpsertTaxInfoParams struct {
	UserID                     uuid.UUID
	GrossMonthlyMinor          int64
	TaxCode                    string
	TaxSystem                  string
	TaxYear                    string
	MaritalStatus              string
	PensionContributionPercent int32
	HasStudentLoan             bool
	StudentLoanPlan            *string
}

func (q *Queries) UpsertTaxInfo(ctx context.Context, arg UpsertTaxInfoParams) (TaxInfo, error) {
	row := q.db.QueryRow(ctx, upsertTaxInfo,
		arg.UserID,
		arg.GrossMonthlyMinor,
		arg.TaxCode,
		arg.TaxSystem,
		arg.TaxYear,
		arg.MaritalStatus,
		arg.PensionContributionPercent,
		arg.HasStudentLoan,
		arg.StudentLoanPlan,
	)
	var i TaxInfo
	err := row.Scan(
		&i.UserID,
		&i.GrossMonthlyMinor,
		&i.TaxCode,
		&i.TaxSystem,
		&i.TaxYear,
		&i.MaritalStatus,
		&i.PensionContributionPercent,
		&i.HasStudentLoan,
		&i.StudentLoanPlan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
