// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM household_members
WHERE household_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountMembers(ctx context.Context, householdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, householdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, needs_percent, wants_percent, savings_percent, requires_approvals, invite_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, needs_percent, wants_percent, savings_percent, requires_approvals, surplus_split_method, invite_code, created_at, updated_at, deleted_at
`

type CreateHouseholdParams struct {
	Name              string
	NeedsPercent      int32
	WantsPercent      int32
	SavingsPercent    int32
	RequiresApprovals bool
	InviteCode        string
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold,
		arg.Name,
		arg.NeedsPercent,
		arg.WantsPercent,
		arg.SavingsPercent,
		arg.RequiresApprovals,
		arg.InviteCode,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NeedsPercent,
		&i.WantsPercent,
		&i.SavingsPercent,
		&i.RequiresApprovals,
		&i.SurplusSplitMethod,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO household_members (household_id, user_id, is_creator)
VALUES ($1, $2, $3)
RETURNING id, household_id, user_id, is_creator, created_at, updated_at, deleted_at
`

type CreateMemberParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	IsCreator   bool
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (HouseholdMember, error) {
	row := q.db.QueryRow(ctx, createMember, arg.HouseholdID, arg.UserID, arg.IsCreator)
	var i HouseholdMember
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.UserID,
		&i.IsCreator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, name, needs_percent, wants_percent, savings_percent, requires_approvals, surplus_split_method, invite_code, created_at, updated_at, deleted_at FROM households WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NeedsPercent,
		&i.WantsPercent,
		&i.SavingsPercent,
		&i.RequiresApprovals,
		&i.SurplusSplitMethod,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHouseholdByInviteCode = `-- name: GetHouseholdByInviteCode :one
SELECT id, name, needs_percent, wants_percent, savings_percent, requires_approvals, surplus_split_method, invite_code, created_at, updated_at, deleted_at FROM households WHERE invite_code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHouseholdByInviteCode(ctx context.Context, inviteCode string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByInviteCode, inviteCode)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NeedsPercent,
		&i.WantsPercent,
		&i.SavingsPercent,
		&i.RequiresApprovals,
		&i.SurplusSplitMethod,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT m.household_id, m.user_id, m.is_creator, h.requires_approvals, h.surplus_split_method,
       h.needs_percent, h.wants_percent, h.savings_percent
FROM household_members m
JOIN households h ON h.id = m.household_id AND h.deleted_at IS NULL
WHERE m.user_id = $1 AND m.deleted_at IS NULL
`

type GetMembershipByUserIDRow struct {
	HouseholdID        uuid.UUID
	UserID             uuid.UUID
	IsCreator          bool
	RequiresApprovals  bool
	SurplusSplitMethod string
	NeedsPercent       int32
	WantsPercent       int32
	SavingsPercent     int32
}

func (q *Queries) GetMembershipByUserID(ctx context.Context, userID uuid.UUID) (GetMembershipByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, userID)
	var i GetMembershipByUserIDRow
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.IsCreator,
		&i.RequiresApprovals,
		&i.SurplusSplitMethod,
		&i.NeedsPercent,
		&i.WantsPercent,
		&i.SavingsPercent,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, m.is_creator, m.created_at AS joined_at, u.name, u.email, u.age, u.gender
FROM household_members m
JOIN users u ON u.id = m.user_id AND u.deleted_at IS NULL
WHERE m.household_id = $1 AND m.deleted_at IS NULL
ORDER BY m.created_at
`

type ListMembersRow struct {
	UserID    uuid.UUID
	IsCreator bool
	JoinedAt  time.Time
	Name      string
	Email     string
	Age       *int32
	Gender    *string
}

func (q *Queries) ListMembers(ctx context.Context, householdID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.IsCreator,
			&i.JoinedAt,
			&i.Name,
			&i.Email,
			&i.Age,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateInviteCode = `-- name: RotateInviteCode :one
UPDATE households SET invite_code = $2 WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, needs_percent, wants_percent, savings_percent, requires_approvals, surplus_split_method, invite_code, created_at, updated_at, deleted_at
`

type RotateInviteCodeParams struct {
	ID         uuid.UUID
	InviteCode string
}

func (q *Queries) RotateInviteCode(ctx context.Context, arg RotateInviteCodeParams) (Household, error) {
	row := q.db.QueryRow(ctx, rotateInviteCode, arg.ID, arg.InviteCode)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NeedsPercent,
		&i.WantsPercent,
		&i.SavingsPercent,
		&i.RequiresApprovals,
		&i.SurplusSplitMethod,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteMember = `-- name: SoftDeleteMember :execrows
UPDATE household_members SET deleted_at = now()
WHERE household_id = $1 AND user_id = $2 AND deleted_at IS NULL AND is_creator = false
`

type SoftDeleteMemberParams struct {
	HouseholdID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) SoftDeleteMember(ctx context.Context, arg SoftDeleteMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMember, arg.HouseholdID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET name                 = coalesce($1, name),
    needs_percent        = coalesce($2, needs_percent),
    wants_percent        = coalesce($3, wants_percent),
    savings_percent      = coalesce($4, savings_percent),
    requires_approvals   = coalesce($5, requires_approvals),
    surplus_split_method = coalesce($6, surplus_split_method)
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, name, needs_percent, wants_percent, savings_percent, requires_approvals, surplus_split_method, invite_code, created_at, updated_at, deleted_at
`

type UpdateHouseholdParams struct {
	Name               *string
	NeedsPercent       *int32
	WantsPercent       *int32
	SavingsPercent     *int32
	RequiresApprovals  *bool
	SurplusSplitMethod *string
	ID                 uuid.UUID
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold,
		arg.Name,
		arg.NeedsPercent,
		arg.WantsPercent,
		arg.SavingsPercent,
		arg.RequiresApprovals,
		arg.SurplusSplitMethod,
		arg.ID,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NeedsPercent,
		&i.WantsPercent,
		&i.SavingsPercent,
		&i.RequiresApprovals,
		&i.SurplusSplitMethod,
		&i.InviteCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
