// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	Name        string
	AmountMinor int64
	Frequency   string
	Category    string
	AddedBy     uuid.UUID
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type ExpenseApproval struct {
	ExpenseID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Household struct {
	ID                 uuid.UUID
	Name               string
	NeedsPercent       int32
	WantsPercent       int32
	SavingsPercent     int32
	RequiresApprovals  bool
	SurplusSplitMethod string
	InviteCode         string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type HouseholdMember struct {
	ID          uuid.UUID
	HouseholdID uuid.UUID
	UserID      uuid.UUID
	IsCreator   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type Income struct {
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	GrossMonthlyMinor int64
	NetMonthlyMinor   int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
}

type Isa struct {
	ID                         uuid.UUID
	HouseholdID                uuid.UUID
	UserID                     uuid.UUID
	Type                       string
	BalanceMinor               int64
	ContributionsThisYearMinor int64
	AnnualAllowanceMinor       int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  *time.Time
}

type MonthlySnapshot struct {
	HouseholdID        uuid.UUID
	Month              pgtype.Date
	TotalExpensesMinor int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type PasswordResetToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Pension struct {
	ID                uuid.UUID
	HouseholdID       uuid.UUID
	UserID            uuid.UUID
	CurrentValueMinor int64
	TargetMinor       int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	FamilyID   uuid.UUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
}

type SavingsPot struct {
	ID                       uuid.UUID
	HouseholdID              uuid.UUID
	Name                     string
	CurrentMinor             int64
	TargetMinor              int64
	MonthlyContributionMinor int64
	Emoji                    string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DeletedAt                *time.Time
}

type TaxInfo struct {
	UserID                     uuid.UUID
	GrossMonthlyMinor          int64
	TaxCode                    string
	TaxSystem                  string
	TaxYear                    string
	MaritalStatus              string
	PensionContributionPercent int32
	HasStudentLoan             bool
	StudentLoanPlan            *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  *time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Age          *int32
	Gender       *string
	Currency     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}
