// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, family_id, expires_at, created_at, revoked_at, replaced_by
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	FamilyID  uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token_hash, user_id, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, expires_at, created_at, revoked_at, replaced_by FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE token_hash = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, tokenHash)
	return err
}

const purgeExpiredRefreshTokens = `-- name: PurgeExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) PurgeExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeExpiredRefreshTokens)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now(), replaced_by = $2 WHERE id = $1
`

type RotateRefreshTokenParams struct {
	ID         uuid.UUID
	ReplacedBy *uuid.UUID
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.ID, arg.ReplacedBy)
	return err
}
